"""first_migration

Revision ID: 9a25cffdb0b8
Revises:
Create Date: 2022-04-21 13:51:09.038398

"""
# revision identifiers, used by Alembic.
revision = "9a25cffdb0b8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
